# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: Issschool

frameworkVersion: '2'

# The `provider` block defines where your service will be deployed
custom:
  bucket: issschool-lambda-example

provider:
  name: aws
  runtime: nodejs14.x
  stackName: register
  stage: dev
  package:
  individually: true
  environment:
      USERS_TABLE: 'users'
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: '*'

# The `functions` block defines what code to deploy
functions:
  create:
    handler: register.signUp
    events:
      - http:
          path: register
          method: post
          cors: true
  login:
    handler: login.login
    events:
      - http:
          path: login
          method: post
          cors: true
  classDetails:
    handler: classDetails.classDetails
    events:
      - http:
          path: classDetails/{name}
          method: get
  classList:
    handler: classDetails.classList
    events:
      - http:
          path: classList
          method: get
  videoList:
    handler: videos.videoList
    events:
      - http:
          path: videoList/{lessonId}
          method: get
  workList:
    handler: videos.workList
    events:
      - http:
          path: workList/{lessonId}
          method: get
  addLoginHistory:
    handler: loginHistory.addLoginHistory
    events:
      - http:
          path: addLoginHistory
          method: post
  deleteLoginHistory:
    handler: loginHistory.deleteLoginHistory
    events:
      - http:
          path: deleteLoginHistory
          method: delete
          cors: true

resources:
  Resources:
    UsersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: email
            AttributeType: S
        KeySchema:
          -
            AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'users'
    LoginHistoryDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: email
            AttributeType: S
        KeySchema:
          -
            AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'login-history'
